#! /usr/bin/env python3

import sys

def factorize(n):
  for i in range(2, n):
    if n % i == 0:
      return (i, n // i)
  return (n, 1)

def main():
  if len(sys.argv) != 2:
    print("Usage: factors <file>")
    sys.exit(1)

  with open(sys.argv[1]) as f:
    for line in f:
      n = int(line.strip())
      p, q = factorize(n)
      print(f"{n}={p}*{q}")

if __name__ == "__main__":
  main()