#!/bin/bash

if [[ $# -ne 1 ]]; then
  echo "Usage: factors <file>"
  exit 1
fi

while read -r line; do
  n=$((line))
  for ((i=2; i<n; i++)); do
    if [[ $((n % i)) -eq 0 ]]; then
      p=$i
      q=$((n / i))
      break
    fi
  done
  if [[ -z $p ]]; then
    p=$n
    q=1
  fi
  echo "$n=$p*$q"
done < "$1"
